apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: ajvideira/conversao-temperatura:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  type: NodePort
  selector:
    app: conversao-temperatura
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
